---
title: "Inter-trial effects in visual search: Factorial comparison of Bayesian updating models"
author: "Fredrik Allenmark, Hermann J. Müller, Zhuanghua Shi"
date: "General and Experimental Psychology, Psychology Department, LMU Munich"
site: bookdown::bookdown_site
bibliography: [bibliography.bib]
---

1.	Experimental Psychology, Department of Psychology, LMU Munich, Germany
2.	Department of Psychological Science, Birkbeck College (University of London), London, UK

# Acknowledgements

This work was supported by German research foundation DFG MU773/16-1 to HJM and DFG SH166/3-1 to ZS. The authors would like to thank Lena Schröder and Kerstin Wenzel for recruiting and testing participants and Uta Noppeney for helpful discussions.

Correspondence concerning this article should be addressed to Zhuanghua Shi, General and Experimental Psychology, Department of Psychology, Ludwig-Maximilians-Universität München, 80802, Munich, Germany. Email: strongway@psy.lmu.de. 

# Abstract

Many previous studies on visual search have reported inter-trial effects, that is, observers respond faster when some target property, such as a defining feature or dimension,  or the response associate with the target repeats versus changes across consecutive trial episodes. However, what processes drive these inter-trial effects is still controversial. Here, we investigated this question using a combination of Bayesian modelling of belief updating and evidence accumulation modelling in perceptual decision-making. 
In three visual singleton (‘pop-out’) search experiments, we explored how the probability of the response-critical states of the search display (e.g., target presence/absence) and the repetition/switch of the target-defining dimension (color/orientation) affect reaction time distributions. The results replicated the mean reaction time (RT) inter-trial and dimension repetition/switch effects that have been reported in previous studies. Going beyond this, to uncover the underlying mechanisms, we used the Drift-Diffusion Model (DDM) and the Linear Approach to Threshold with Ergodic Rate model (LATER) to explain the RT distributions in terms of decision bias (starting point) and information processing speed (evidence accumulation rate). 
We further investigated how these different aspects of the decision-making process are affected by different properties of stimulus history, giving rise to dissociable inter-trial effects. We approached this question by (i) combining each perceptual decision making model (DDM or LATER) with different updating models, each specifying a plausible rule for updating of either the starting point or the rate, based on stimulus history, and (ii) comparing every possible combination of trial-wise updating mechanism and perceptual decision model in a factorial model comparison.
Consistently across experiments, we found that the (recent) history of the response-critical property influences the initial decision bias, while repetition/switch of the target-defining dimension affects the accumulation rate, reflecting the top-down modulation process. This provides strong evidence of a disassociation between response- and dimension-based inter-trial effects.

